### ISSUE TITLE
Expense Accounts

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#10]
Al elegir un tax para el expense account, deshabilita el campo exenta al cargar una compra.

**Comment by leonardoyegros** [comment]
Resuelto. Por mas que la expensa tenga asignado un impuesto se permite insertar precio exento en compras y ventas.

**Comment by leonardoyegros** [comment]
Me notifica aca! jaja


*Leonardo Martinez*

2015-09-03 9:28 GMT-04:00 avallese <notifications@github.com>:
