### ISSUE TITLE
Ventas: Tipos de Cambios

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#11]
Una venta tiene dos tipos de cambios:
1- La de la factura: que SIEMPRE convierte a moneda local (main currency) por motivos fiscales.
2- La del cobro: que SOLO convierte si la moneda de la factura difiere a la moneda de la cuenta de fondo. Por ejemplo: se factura en dólares y se cobra en guaraníes.
Por lo tanto, en la imagen en adjunto no se debe realizar la operación de cambio de la cuenta de fondo porque tanto la factura como la cuenta de fondo son en USD.
Para más información mirar la planilla del google drive "Ejemplo Compras" 
![screen shot 2015-09-08 at 15 32 41](https://cloud.githubusercontent.com/assets/14109935/9745300/df317652-563e-11e5-8af3-d5db5249cdda.png)

**Comment by leonardoyegros** [comment]
Si la venta es en dolares, y la cuenta de fondo tb, el tipo de cambio es 1? @avallese @alessandra

**Comment by leonardoyegros** [comment]
I think you should use an
`<addr>` element here instead.

**Comment by avallese** [comment]
Este issue no está closed todavía. 
Sigue apareciendo mal la parte de tipos de cambios de la cuenta de fondo. Ahora mismo está apareciendo al revés de como debería.

**Comment by leonardoyegros** [comment]
*Ahora Si!*
