### ISSUE TITLE
Users: Add Users

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#15]
Sale "Null"  cuando se agrega un user nuevo y no llega la invitación al email.

![image](https://cloud.githubusercontent.com/assets/14109935/9801145/4e7e72c0-57df-11e5-8ef2-77619df35965.png)

**Comment by leonardoyegros** [comment]
Se quito el boton.

El campo de <strong>E-mail</strong> funciona de la siguiente forma:

1- Caso uno, el email ingresado existe, al seleccionar automáticamente se te asigna el usuario.
2- El E-mail es válido y no existe, se envía una invitación.
3- El E-mail es inválido, se notifica en la interfaz.
