### ISSUE TITLE
List Purchases: Debe estirar en moneda local la conversión

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#24]
Debe estirar en moneda local la conversión o sino no sirve la sumatoria porque esta sumando distintas monedas.
![image](https://cloud.githubusercontent.com/assets/14109935/9905755/c8398c20-5c54-11e5-9e21-a252bc776b69.png)

**Comment by leonardoyegros** [comment]
Está estirando. El problema era que no se guardaba el tipo de cambio de la compra. Siempre guardaba con valor 1
