### ISSUE TITLE
List Purchase: no convierte a Moneda Local

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#26]
Sale todavía en moneda extranjera en las columnas de IVA.
![image](https://cloud.githubusercontent.com/assets/14109935/9936625/de8356ba-5d2a-11e5-89c0-1ac6d73ba660.png)

Fijate en las columnas y como sale en mi libro Ventas , así mismo debe estar el libro compras (hay una columna de total en moneda extranjera, luego estas los IVAs y al final el total en moneda local)
![image](https://cloud.githubusercontent.com/assets/14109935/9936655/042ffd3c-5d2b-11e5-8eab-0f755910d892.png)

**Comment by leonardoyegros** [comment]
Le falta
