### ISSUE TITLE
Edit Sale: La edición de una venta duplica el valor en el campo "Monto".

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#29]
El monto duplicado sale en el campo "Monto" y en "List Sales".
![screen shot 2015-09-18 at 16 55 44](https://cloud.githubusercontent.com/assets/14109935/9970918/653e8e6c-5e26-11e5-9d06-957f391661a0.png)

![image](https://cloud.githubusercontent.com/assets/14109935/9970945/8f590b6e-5e26-11e5-9571-0f4c9e9a040d.png)

**Comment by leonardoyegros** [comment]
Vos eliminaste la expensa y luego agregaste otra con el mismo valor verdad?

Ya se que pudo haber pasado. Creo que hiciste eso y al momento de
actualizar los montos no se borro de la base de datos todavia lo que
borraste y se quedo sumando doble.


*Leonardo Martinez*

2015-09-18 16:59 GMT-04:00 avallese <notifications@github.com>:

**Comment by avallese** [comment]
Si, hice eso mismo dos veces jaja
Probé eliminar la expensa y cargar de nuevo con el mismo valor.

**Comment by leonardoyegros** [comment]
Ya subi la corrección. Podrías editar de nuevo?


*Leonardo Martinez*

2015-09-21 10:46 GMT-04:00 avallese <notifications@github.com>:

**Comment by avallese** [comment]
Probamos editar y ya no genera el error.
Gracias!

**Comment by avallese** [comment]
Ahora sale un error en el "List Sales"
Salen todas las ventas con el mismo monto de la venta que editamos: 35.449.047
![image](https://cloud.githubusercontent.com/assets/14109935/9996728/5db3d7e2-6056-11e5-9c71-01cfe45391e1.png)

**Comment by leonardoyegros** [comment]
Corregido.


*Leonardo Martinez*

2015-09-21 11:47 GMT-04:00 avallese <notifications@github.com>:
