### ISSUE TITLE
Tipos de cambios: Realiza la conversión en la cuenta de fondo, cuando la moneda de la factura es igual a la moneda de la cuenta de fondo.

### ISSUE THREAD

**Issue by avallese** [leonardoyegros/siso1.3#30]
Realiza la conversión en la cuenta de fondo, cuando la moneda de la factura es igual a la moneda de la cuenta de fondo.
Factura por 1.000 USD, se paga 1.000 USD.
Tipo de cambio en "Monedas" = 5.500
Tipo de cambio en factura  = 5.400
Realiza esta operación = (1000*5400)/5500
Entonces la cuenta de fondo sale = 981.81 USD
Deberia salir por 1.000 USD porque cuando la moneda de la factura y la moneda de la cuenta de fondo son iguales, entonces el tipo de cambio de la cuenta de fondo = 1
Ejemplo: Así sale
![image](https://cloud.githubusercontent.com/assets/14109935/9993373/71eafc6a-6045-11e5-8732-548d270ab402.png)
Ejemplo: Así debería salir
![image](https://cloud.githubusercontent.com/assets/14109935/9993387/809769c4-6045-11e5-9d63-6800c3b9958a.png)

**Comment by leonardoyegros** [comment]
Y en ese caso, si cambias la cotización de la moneda en la cuenta de fondo que debe pasar?

**Comment by avallese** [comment]
Hola Leo! se puede no cerrar un issue cuando se comenta? porque si cerras entonces no le puedo dar seguimiento.
Este issue por ejemplo sigue abierto. 
No deberías cambiar la cotización de la cuenta de fondo si es igual a la moneda de la factura. Porque debería quedar en 1. 
Ejemplo: 
Si la factura es por 1500 USD =
Tipo de cambio fiscal (para presentar impuesto se debe convertir a moneda nacional) = 5.400
Tipo de cambio de la cuenta de fondo (si es en USD) = 1 
Así sale:
![image](https://cloud.githubusercontent.com/assets/14109935/10101083/5f2d6294-6364-11e5-9c5a-fd0a3c381546.png)
Así debería salir:
![image](https://cloud.githubusercontent.com/assets/14109935/10101110/829d07f2-6364-11e5-96d3-74b3f881ffdc.png)
